package sfmotion;

public class CaseManagementConferenceEntry extends SFMotionEntry {
	/**
	 * 	CASE MANAGEMENT CONFERENCE SET FOR MAY-09-2018 AT 10:30 AM IN DEPARTMENT 610 FOR THE SUBMISSION OF CASE MANAGEMENT STATEMENTS. THE APR-10-2018 ORDER TO SHOW CAUSE IS OFF CALENDAR. NOTICE SENT BY COURT.
		CASE MANAGEMENT CONFERENCE OF MAY-09-2018 CONTINUED TO JUN-13-2018 AT 10:30 AM IN DEPARTMENT 610 FOR STATUS OF CONSOLIDATION. NOTICE SENT BY COURT.
		CASE MANAGEMENT CONFERENCE IS HELD ON MAY-30-2017 MATTER IS SET FOR FURTHER CASE MANAGEMENT CONFERENCE ON AUG-07-2017 AT 2:00 PM IN 304. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER BETH E. GRANT CSR #10943
		CASE MANAGEMENT CONFERENCE IS HELD ON AUG-07-2017. MATTER IS SET FOR FURTHER CASE MANAGEMENT CONFERENCE TO OCT-13-2017 AT 9:00 AM IN 304. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER TAMARA WILLAT CSR #4609.
		CASE MANAGEMENT CONFERENCE IS HELD ON OCT-13-2017. THE MATTER IS SET FOR FURTHER CASE MANAGEMENT CONFERENCE ON NOV-08-2017 AT 3:00 PM IN 304. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER ANGELA M. RODRIQUEZ CSR #14060.
		CASE MANAGEMENT CONFERENCE IS HELD ON NOV-8-2017. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER ANGELA M. RODRIGUEZ CSR #14060
		CASE MANAGEMENT CONFERENCE HELD ON DEC-27-2017. MATTER IS SET FOR FURTHER CASE MANAGEMENT CONFERENCE ON MAR-15-2018 AT 2:00 PM IN 304. JUDGE KURTIS E.A KARNOW; CLERKS DANIAL LEMIRE AND WILLIAM TRUPEK; COURT REPORTER SHEILA PHAM CSR# 13293
		CASE MANAGEMENT CONFERENCE AND MOTION HEARING SET FOR MAR-15-2018 CONTINUED TO APR-09-2018 AT 2:00 PM IN 304 BY THE COURT DUE TO UNAVOIDABLE SCHEDULING ISSUE.
		CASE MANAGEMENT CONFERENCE HEARING ON MOTIONS TO STRIKE HELD ON APR-09-2018. THE MOTIONS ARE ARGUED IN OPEN COURT ON THE RECORD AND TAKEN UNDER SUBMISSION. THE MATTER IS SET FOR FURTHER CASE MANAGEMENT CONFERENCE ON JUN-06-2018 AT 2:00 PM IN 304. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER LANA LOPER CSR 667
		CASE MANAGEMENT CONFERENCE IS HELD ON JUN-06-2018. MATTER IS SET FOR FURTHER CASE MANAGEMENT CONFERENCE ON JUL-13-2018 AT 3:00 PM IN 304. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER MARY VISCIGLIO CSR #10391
		CASE MANAGEMENT CONFERENCE AND CONTINUED HEARING ON MOTION TO CONTINUE TRIAL DATE IS HELD ON AUG-03-2018. THE MOTION IS TAKEN UNDER SUBMISSION. JUDGE CURTIS E.A. KARNOW, CLERK DANIAL LEMIRE, REPORTER BETH E. GRANT CSR #10943.
	*/
	SFMotionEntry entry;

	public CaseManagementConferenceEntry(String _sdate, String _text) {
		super(_sdate, _text, CASE_MANAGEMENT_CONFERENCE);
	}

	public static CaseManagementConferenceEntry parse(String _sdate, String _text) {
		if (!_text.startsWith("CASE MANAGEMENT CONFERENCE")) {
			return null;
		}
		// do nothing for now:
		return new CaseManagementConferenceEntry(_sdate, _text);
	}
}
